- src/main/java/com/neemshade/sniper/repository/TaskGroupRepository.java
- src/main/java/com/neemshade/sniper/service/ExtTaskService.java
- src/main/java/com/neemshade/sniper/web/rest/ExtTaskResource.java
- src/main/resources/.h2.server.properties
- src/main/webapp/app/entities/entity.module.ts
- src/main/webapp/app/entities/ext-task/downloader/downloader.component.html
- src/main/webapp/app/entities/ext-task/downloader/downloader.component.ts
- src/main/webapp/app/entities/ext-task/ext-task-group-detail/ext-task-group-detail.component.html
- src/main/webapp/app/entities/ext-task/ext-task-group-detail/ext-task-group-detail.component.ts
- src/main/webapp/app/entities/ext-task/ext-task-group-list/ext-task-group-list.component.html
- src/main/webapp/app/entities/ext-task/ext-task-group-list/ext-task-group-list.component.ts
- src/main/webapp/app/entities/ext-task/ext-task-list-template/ext-task-list-template.component.html
- src/main/webapp/app/entities/ext-task/ext-task-list-template/ext-task-list-template.component.ts
- src/main/webapp/app/entities/ext-task/ext-task-list/ext-task-list.component.html
- src/main/webapp/app/entities/ext-task/ext-task-list/ext-task-list.component.ts
- src/main/webapp/app/entities/ext-task/ext-task-routing.module.ts
- src/main/webapp/app/entities/ext-task/ext-task.module.ts
- src/main/webapp/app/entities/ext-task/ext-task.service.ts
- src/main/webapp/app/entities/ext-task/help/help.component.html
- src/main/webapp/app/entities/ext-task/help/help.component.ts
- src/main/webapp/app/entities/ext-task/index.ts
- src/main/webapp/app/entities/ext-task/purge/purge.component.html
- src/main/webapp/app/entities/ext-task/purge/purge.component.ts
- src/main/webapp/app/entities/ext-task/uploader/uploader.component.html
- src/main/webapp/app/entities/ext-task/uploader/uploader.component.ts
- src/main/webapp/app/entities/task-group/task-group.service.ts
- src/main/webapp/app/layouts/navbar/navbar.component.html
displays task groups within the date range
> Task group list with date range option

- src/main/java/com/neemshade/sniper/config/ExtServletConfig.java
- src/main/java/com/neemshade/sniper/repository/TaskRepository.java
- src/main/java/com/neemshade/sniper/service/ExtUploaderService.java
- src/main/java/com/neemshade/sniper/service/TaskService.java
- src/main/java/com/neemshade/sniper/service/filemetrics/SnM4aManager.java
- src/main/java/com/neemshade/sniper/service/filemetrics/SnMp3Manager.java
- src/main/java/com/neemshade/sniper/web/rest/ExtTaskResource.java
- src/main/webapp/app/entities/ext-task/ext-task-group-detail/ext-task-group-detail.component.html
- src/main/webapp/app/entities/ext-task/ext-task-group-detail/ext-task-group-detail.component.ts
- src/main/webapp/app/entities/ext-task/ext-task-group-list/ext-task-group-list.component.html
- src/main/webapp/app/entities/ext-task/ext-task-group-list/ext-task-group-list.component.ts
- src/main/webapp/app/entities/ext-task/ext-task-list-template/ext-task-list-template.component.html
- src/main/webapp/app/entities/ext-task/ext-task-list-template/ext-task-list-template.component.ts
- src/main/webapp/app/entities/ext-task/ext-task.service.ts
- src/main/webapp/app/entities/ext-task/help/help.component.html
- src/main/webapp/app/entities/ext-task/uploader/uploader.component.html
- src/main/webapp/app/entities/ext-task/uploader/uploader.component.scss
- src/main/webapp/app/entities/ext-task/uploader/uploader.component.ts
- src/main/webapp/app/layouts/navbar/navbar.component.html
upload to different dir
task detail page to child task list template page communication
> UploadInRootDir

- src/main/resources/.h2.server.properties
- src/main/webapp/app/entities/ext-task/ext-task-group-detail/ext-task-group-detail.component.ts
- src/main/webapp/app/entities/ext-task/ext-task-list-template/ext-task-list-template.component.html
- src/main/webapp/app/entities/ext-task/ext-task-list-template/ext-task-list-template.component.ts
display task list in the template
> Tasklisttemplatebug1

- src/main/java/com/neemshade/sniper/service/ExtTaskService.java
- src/main/java/com/neemshade/sniper/web/rest/ExtTaskResource.java
- src/main/webapp/app/entities/ext-task/ext-task-group-detail/ext-task-group-detail.component.ts
- src/main/webapp/app/entities/ext-task/ext-task-list-template/ext-task-list-template.component.html
- src/main/webapp/app/entities/ext-task/ext-task-list-template/ext-task-list-template.component.ts
- src/main/webapp/app/entities/ext-task/ext-task.service.ts
able to pass tasks, historyObe, fieldNames to update function
> multiParamHandleWhileTasksUpdate

- src/main/java/com/neemshade/sniper/repository/SnFileBlobRepository.java
- src/main/java/com/neemshade/sniper/repository/SnFileRepository.java
- src/main/java/com/neemshade/sniper/repository/TaskHistoryRepository.java
- src/main/java/com/neemshade/sniper/repository/TaskRepository.java
- src/main/java/com/neemshade/sniper/service/ExtDownloaderService.java
- src/main/java/com/neemshade/sniper/service/ExtTaskService.java
- src/main/java/com/neemshade/sniper/service/SnFileService.java
- src/main/java/com/neemshade/sniper/service/TaskService.java
- src/main/java/com/neemshade/sniper/web/rest/ExtTaskResource.java
- src/main/webapp/app/entities/ext-task/downloader/downloader.component.html
- src/main/webapp/app/entities/ext-task/downloader/downloader.component.ts
- src/main/webapp/app/entities/ext-task/ext-task-group-detail/ext-task-group-detail.component.html
- src/main/webapp/app/entities/ext-task/ext-task-group-detail/ext-task-group-detail.component.ts
- src/main/webapp/app/entities/ext-task/ext-task-group-list/ext-task-group-list.component.html
- src/main/webapp/app/entities/ext-task/ext-task-group-list/ext-task-group-list.component.ts
- src/main/webapp/app/entities/ext-task/ext-task-list-template/ext-task-list-template.component.html
- src/main/webapp/app/entities/ext-task/ext-task-list-template/ext-task-list-template.component.ts
- src/main/webapp/app/entities/ext-task/ext-task.service.ts
- src/main/webapp/app/entities/ext-task/help/help.component.html
- src/main/webapp/app/entities/ext-task/uploader/uploader.component.html
- src/main/webapp/app/entities/ext-task/uploader/uploader.component.ts
download files of taskGroup, task and selectedTasks
> downloadFiles

- src/main/java/com/neemshade/sniper/service/ExtTaskService.java
- src/main/java/com/neemshade/sniper/service/TaskService.java
- src/main/java/com/neemshade/sniper/web/rest/ExtTaskResource.java
- src/main/webapp/app/entities/ext-task/ext-task-group-detail/ext-task-group-detail.component.html
- src/main/webapp/app/entities/ext-task/ext-task-group-detail/ext-task-group-detail.component.ts
- src/main/webapp/app/entities/ext-task/ext-task-list-template/ext-task-list-template.component.ts
- src/main/webapp/app/entities/ext-task/ext-task.service.ts
- src/main/webapp/app/entities/ext-task/help/help.component.html
moved code from taskGroup detail page to template page
in the server side, made findTasks a generic fn to load any kind of task
list
> revampTemplate

- src/main/java/com/neemshade/sniper/repository/TaskRepository.java
- src/main/java/com/neemshade/sniper/service/ExtTaskService.java
- src/main/java/com/neemshade/sniper/service/TaskService.java
- src/main/webapp/app/entities/ext-task/ext-task-list-template/ext-task-list-template.component.html
- src/main/webapp/app/entities/ext-task/ext-task-list-template/ext-task-list-template.component.ts
active and all task list display
> dualTaskLists

- src/main/webapp/app/entities/ext-task/ext-task-list/ext-task-list.component.html
- src/main/webapp/app/entities/ext-task/ext-task-list/ext-task-list.component.ts
> addendumToTaskListCommit

- src/main/java/com/neemshade/sniper/web/rest/ExtTaskResource.java
- src/main/webapp/app/entities/ext-task/ext-task-group-list/ext-task-group-list.component.ts
- src/main/webapp/app/entities/ext-task/ext-task-list-template/ext-task-list-template.component.html
- src/main/webapp/app/entities/ext-task/ext-task-list-template/ext-task-list-template.component.ts
- src/main/webapp/app/entities/ext-task/ext-task.service.ts
- src/main/webapp/app/layouts/footer/footer.component.html
task group and task list tables need to have pagination buttons
> footerNumbers

- src/main/resources/.h2.server.properties
- src/main/webapp/app/entities/ext-task/ext-task-list-template/ext-task-list-template.component.html
> changed columns

- src/main/java/com/neemshade/sniper/repository/PatientRepository.java
- src/main/java/com/neemshade/sniper/service/ExtTaskService.java
minor addition of director and patient
> DirectorAdded

- src/main/java/com/neemshade/sniper/service/ExtUploaderService.java
- src/main/webapp/app/entities/ext-task/ext-history/ext-history.component.html
- src/main/webapp/app/entities/ext-task/ext-history/ext-history.component.ts
- src/main/webapp/app/entities/ext-task/ext-sn-file/ext-sn-file.component.html
- src/main/webapp/app/entities/ext-task/ext-sn-file/ext-sn-file.component.ts
- src/main/webapp/app/entities/ext-task/ext-task-list-template/ext-task-list-template.component.html
- src/main/webapp/app/entities/ext-task/ext-task-list-template/ext-task-list-template.component.ts
- src/main/webapp/app/entities/ext-task/ext-task-routing.module.ts
- src/main/webapp/app/entities/ext-task/ext-task.module.ts
- src/main/webapp/app/entities/ext-task/index.ts
- src/main/webapp/app/entities/user-info/user-info-dialog.component.html
- src/main/webapp/app/entities/user-info/user-info-dialog.component.ts
attempted to display snFile and history in pop-up
need to debug
> displaySnFiles

- src/main/java/com/neemshade/sniper/repository/TaskRepository.java
- src/main/java/com/neemshade/sniper/service/TaskService.java
- src/main/java/com/neemshade/sniper/web/rest/ExtTaskResource.java
- src/main/webapp/app/entities/ext-task/ext-task-group-detail/ext-task-group-detail.component.html
- src/main/webapp/app/entities/ext-task/ext-task-group-detail/ext-task-group-detail.component.ts
- src/main/webapp/app/entities/ext-task/ext-task.service.ts
draw a graph with the status of available tasks
> statusChart

- src/main/webapp/app/entities/ext-task/ext-task-list-template/ext-task-list-template.component.html
- src/main/webapp/app/entities/ext-task/ext-task-list-template/ext-task-list-template.component.ts
> checkboxFunction

- src/main/java/com/neemshade/sniper/service/ExtTaskService.java
- src/main/java/com/neemshade/sniper/service/ExtUploaderService.java
- src/main/java/com/neemshade/sniper/web/rest/ExtTaskResource.java
- src/main/resources/.h2.server.properties
- src/main/webapp/app/entities/ext-task/ext-sn-file/ext-sn-file.component.html
- src/main/webapp/app/entities/ext-task/ext-sn-file/ext-sn-file.component.ts
- src/main/webapp/app/entities/ext-task/ext-task.service.ts
- src/main/webapp/app/entities/sn-file/sn-file.model.ts
added logic for merge and clone
> mergeClone

- src/main/java/com/neemshade/sniper/service/ExtTaskService.java
- src/main/java/com/neemshade/sniper/service/ExtUploaderService.java
- src/main/resources/config/application-prod.yml
- src/main/webapp/app/entities/ext-task/ext-sn-file/ext-sn-file.component.ts
- src/main/webapp/app/entities/ext-task/ext-task-routing.module.ts
adjust the line count when the file is uploaded
> adjustLineCount

- src/main/webapp/app/entities/ext-task/ext-task-list-template/ext-task-list-template.component.html
- src/main/webapp/app/entities/ext-task/ext-task-list-template/ext-task-list-template.component.ts
- src/main/webapp/app/entities/task/task.model.ts
> Menu created

- src/main/java/com/neemshade/sniper/repository/TaskRepository.java
- src/main/java/com/neemshade/sniper/service/ExtTaskService.java
- src/main/java/com/neemshade/sniper/service/SnFileService.java
- src/main/java/com/neemshade/sniper/service/TaskService.java
- src/main/java/com/neemshade/sniper/web/rest/ExtTaskResource.java
- src/main/resources/.h2.server.properties
- src/main/webapp/app/entities/ext-task/ext-sn-file/ext-sn-file.component.html
- src/main/webapp/app/entities/ext-task/ext-sn-file/ext-sn-file.component.ts
- src/main/webapp/app/entities/ext-task/ext-task.service.ts
overcame the relationship deletion operation
> snFileUpdateSuccessful

- src/main/webapp/app/entities/ext-task/ext-task-list-template/ext-task-list-template.component.html
- src/main/webapp/app/entities/ext-task/ext-task-list-template/ext-task-list-template.component.ts
selectAllCheckBox and its Function
> selectAllCheckBox and its Function

- src/main/resources/config/application-prod.yml
- src/main/webapp/app/entities/ext-task/downloader/downloader.component.ts
- src/main/webapp/app/entities/ext-task/ext-history/ext-history.component.ts
- src/main/webapp/app/entities/ext-task/ext-sn-file/ext-sn-file.component.ts
- src/main/webapp/app/entities/ext-task/ext-task-group-detail/ext-task-group-detail.component.ts
- src/main/webapp/app/entities/ext-task/ext-task-group-list/ext-task-group-list.component.html
- src/main/webapp/app/entities/ext-task/ext-task-group-list/ext-task-group-list.component.ts
- src/main/webapp/app/entities/ext-task/ext-task-list-template/ext-task-list-template.component.html
- src/main/webapp/app/entities/ext-task/ext-task-list-template/ext-task-list-template.component.ts
- src/main/webapp/app/entities/ext-task/ext-task-list/ext-task-list.component.html
- src/main/webapp/app/entities/ext-task/ext-task-list/ext-task-list.component.ts
- src/main/webapp/app/entities/ext-task/ext-task.module.ts
- src/main/webapp/app/entities/ext-task/ext-task.service.ts
- src/main/webapp/app/entities/ext-task/uploader/uploader.component.ts
cleaned up the code and made ready for production
> prodRelatedChangesFixes

- src/main/webapp/app/entities/ext-task/ext-sn-file/ext-sn-file.component.html
- src/main/webapp/app/entities/ext-task/ext-sn-file/ext-sn-file.component.scss
- src/main/webapp/app/entities/ext-task/ext-sn-file/ext-sn-file.component.ts
- src/main/webapp/app/entities/ext-task/ext-task-group-detail/ext-task-group-detail.component.html
- src/main/webapp/app/entities/ext-task/ext-task-list-template/ext-task-list-template.component.html
- src/main/webapp/app/entities/ext-task/ext-task-list-template/ext-task-list-template.component.scss
- src/main/webapp/app/entities/ext-task/ext-task-list-template/ext-task-list-template.component.ts
in snFile and template, some of the lines were wrapped down.   Applied
no-wrap on them
the three icons were placed on same line
> columnWidthFix

- src/main/java/com/neemshade/sniper/config/ExtServletConfig.java
- src/main/resources/config/application-prod.yml
- src/main/webapp/app/entities/ext-task/downloader/downloader.component.html
- src/main/webapp/app/entities/ext-task/ext-task-group-detail/ext-task-group-detail.component.html
- src/main/webapp/app/entities/ext-task/ext-task-group-detail/ext-task-group-detail.component.ts
- src/main/webapp/app/entities/ext-task/ext-task-list-template/ext-task-list-template.component.html
- src/main/webapp/app/entities/ext-task/ext-task-list-template/ext-task-list-template.component.ts
- src/main/webapp/app/entities/ext-task/ext-task.service.ts
- src/main/webapp/app/entities/ext-task/help/help.component.html
- src/main/webapp/app/entities/ext-task/uploader/uploader.component.html
- src/main/webapp/app/home/home.component.html
color code for task status
revamp drop down parameters
upload limit setting
> fixColorCode

- src/main/java/com/neemshade/sniper/aop/logging/LoggingAspect.java
- src/main/java/com/neemshade/sniper/web/rest/ExtTaskResource.java
- src/main/webapp/app/entities/ext-task/downloader/downloader.component.html
- src/main/webapp/app/entities/ext-task/downloader/downloader.component.ts
- src/main/webapp/app/entities/ext-task/ext-task-list-template/ext-task-list-template.component.html
- src/main/webapp/app/entities/ext-task/ext-task-list-template/ext-task-list-template.component.ts
- src/main/webapp/app/entities/ext-task/help/help.component.html
change the way drop down menus are displayed
> dropDownMenuReVamp

- src/main/java/com/neemshade/sniper/service/ExtTaskService.java
- src/main/webapp/app/entities/ext-task/ext-task-group-detail/ext-task-group-detail.component.html
- src/main/webapp/app/entities/ext-task/ext-task-list-template/ext-task-list-template.component.html
we had progress bar in task group list page in vertical format.  Added
horizontal format too
Justin can decide between one.
task list table has created time.  "no wrap" style is added
> progressBarOrientation

- src/main/java/com/neemshade/sniper/service/ExtDownloaderService.java
- src/main/java/com/neemshade/sniper/web/rest/ExtTaskResource.java
- src/main/webapp/app/entities/ext-task/downloader/downloader.component.ts
- src/main/webapp/app/entities/ext-task/ext-task-group-detail/ext-task-group-detail.component.html
- src/main/webapp/app/entities/ext-task/ext-task.service.ts
the data from task group is placed into xlsx file
> exportXlsx

- .jhipster/Doctor.json
- .jhipster/Hospital.json
- src/main/java/com/neemshade/sniper/domain/Doctor.java
- src/main/java/com/neemshade/sniper/domain/Hospital.java
- src/main/java/com/neemshade/sniper/service/ExtUploaderService.java
- src/main/resources/config/liquibase/changelog/20180410082708_changelog.xml
- src/main/resources/config/liquibase/master.xml
- src/main/webapp/app/entities/doctor/doctor-detail.component.html
- src/main/webapp/app/entities/doctor/doctor-dialog.component.html
- src/main/webapp/app/entities/doctor/doctor.component.html
- src/main/webapp/app/entities/doctor/doctor.model.ts
- src/main/webapp/app/entities/hospital/hospital-detail.component.html
- src/main/webapp/app/entities/hospital/hospital-dialog.component.html
- src/main/webapp/app/entities/hospital/hospital.component.html
- src/main/webapp/app/entities/hospital/hospital.model.ts
- src/model/sniper.jh
- src/test/java/com/neemshade/sniper/web/rest/DoctorResourceIntTest.java
- src/test/java/com/neemshade/sniper/web/rest/HospitalResourceIntTest.java
doctor and hospital added with chosenType field
when files are uploaded, the chosenType is assigned from doctor or
hospital
> chosenType4Doctors

- src/main/java/com/neemshade/sniper/service/ExtDownloaderService.java
- src/main/java/com/neemshade/sniper/web/rest/ExtTaskResource.java
- src/main/webapp/app/entities/ext-task/downloader/downloader.component.ts
- src/main/webapp/app/entities/ext-task/ext-task-group-detail/ext-task-group-detail.component.html
allow manager to download files that are uploaded by editor
> downloadEditorFiles

- src/main/webapp/app/entities/ext-task/uploader/uploader.component.html
- src/main/webapp/app/entities/ext-task/uploader/uploader.component.ts
allow MT to upload only doc files
> filterUploader

- src/main/java/com/neemshade/sniper/service/ExtUploaderService.java
- src/main/webapp/app/entities/ext-task/ext-sn-file/ext-sn-file.component.ts
> fix_exception

- src/main/java/com/neemshade/sniper/service/ExtDownloaderService.java
- src/main/webapp/app/entities/ext-task/ext-task-list-template/ext-task-list-template.component.html
remove task_id folder name in the downloaded zip file
remove peck_order and change position of id
> flat folder in the zip
